core_home:
    resource: "@CoreBundle/Controller/"
    type:    annotation
    prefix:   /

commu_home:
    resource: "@CommuBundle/Controller/"
    type:     annotation
    prefix:   /communaute

team_home:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /Blog

boutique_home:
    resource: "@BoutiqueBundle/Controller/"
    type:     annotation
    prefix:   /shop

# DÃ©finition route FOSUserBundle #

fos_bundle:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
